on: [workflow_dispatch]
name: deploy-Standard-Azure-Landing-Zone
 
env:
    ENVIRONMENT: nonprod

jobs:
  build-Azure-Landing-Zone:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: action/checkout@v3
      with:
        path: repo
        
    # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    # Deploy Network module
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        template: ./1.Basic Infra/1. Connectivity/main.bicep
        parameters: evironmentType=${{ env.ENVIRONMENT }}
