name: deploy-Standard-Azure-Landing-Zone

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
  
env:
    ENVIRONMENT: nonprod
  
jobs:
  build-Azure-Landing-Zone:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
      with:
        path: repo
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ seccrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@vv1
      with:
        deploymentName: ${{ github.run_number }}
        template: ./1.Basic Infra/1. Connectivity/main.bicep
        parameters: evironmentType=${{ env.ENVIRONMENT }}
